- name: Condition demo
  hosts: localhost
  connection: local
  tasks:
    - name: x is greater than 10
      ansible.builtin.debug:
        msg: "x is greater than 10 "

    - name: x is lesser than 10
      ansible.builtin.debug:
        msg: "x is lesser than 10 "
